name: Code check

on:
  pull_request:
    branches: ["*"]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  codecheck:
    name: Code check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install NPM Dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Build
        run: npm run build
