name: Main

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  main:
    name: Create Release Pull Request or Publish
    runs-on: ubuntu-latest
    outputs:
      published: ${{ steps.changesets.outputs.published }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install NPM Dependencies
        run: npm install

      - name: Create Version PR or Publish
        id: changesets
        uses: changesets/action@v1.4.1
        with:
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
