name: Release - Beta

on:
  pull_request:
    branches:
      - main
jobs:
  prerelease:
    name: Build a beta release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install NPM Dependencies
        run: npm install

      - name: Modify package.json version
        run: node .github/version-script-beta.js

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
