name: Release to AWS

on:
  release:
    types: [published]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  aws:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    steps:
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        run: |
          # Build a docker container and
          echo ${{ github.event.release.tag_name }}
