name: Test version

on:
  push:
    branches:
      - test

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test-version:
    name: Test version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"

      - name: Install NPM Dependencies
        run: npm install

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Test version
        run: |
          echo "Version: ${{ steps.package-version.outputs.current-version }}"
